version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      # Copy .env.example to .env
      - echo Copying .env.example to .env...
      - cp .env.example .env

      # Replace VITE_APP_API_URL with the value from environment variable
      - echo Updating VITE_APP_API_URL in .env...
      - sed -i "s|VITE_APP_API_URL=.*|VITE_APP_API_URL=$VITE_APP_API_URL|g" .env
  build:
    commands:
      # Build the React project
      - echo Building the project...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - node_modules/**/*
